name: aliasgo
base: core24
adopt-info: aliasgo
summary: Configure multi-level bash aliases through yaml.
description: |
  Aliasgo allows you to configure multi-level bash aliases through yaml. It reads yaml in from stdin and writes bash source code to stdout.

grade: stable
confinement: strict

apps:
  aliasgo:
    command: bin/aliasgo

parts:
  aliasgo:
    plugin: go
    build-snaps: [go/latest/stable]
    source: https://github.com/ricky0123/aliasgo
    source-type: git
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version \
      "$(git describe --long --tags --always --match=v*.*.* | sed 's/v//')"
